In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df= pd.read_csv('train.csv')

In [4]:
df.head()

id  feat_1  feat_2  feat_3  feat_4  feat_5  feat_6  feat_7  feat_8  feat_9  \
0   1       1       0       0       0       0       0       0       0       0   
1   2       0       0       0       0       0       0       0       1       0   
2   3       0       0       0       0       0       0       0       1       0   
3   4       1       0       0       1       6       1       5       0       0   
4   5       0       0       0       0       0       0       0       0       0   

    ...     feat_85  feat_86  feat_87  feat_88  feat_89  feat_90  feat_91  \
0   ...           1        0        0        0        0        0        0   
1   ...           0        0        0        0        0        0        0   
2   ...           0        0        0        0        0        0        0   
3   ...           0        1        2        0        0        0        0   
4   ...           1        0        0        0        0        1        0   

   feat_92  feat_93   target  
0        0        0  Class_1  
1        0        0  Class_1  
2        0        0  Class_1  
3        0        0  Class_1  
4        0        0  Class_1  

[5 rows x 95 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61878 entries, 0 to 61877
Data columns (total 95 columns):
id         61878 non-null int64
feat_1     61878 non-null int64
feat_2     61878 non-null int64
feat_3     61878 non-null int64
feat_4     61878 non-null int64
feat_5     61878 non-null int64
feat_6     61878 non-null int64
feat_7     61878 non-null int64
feat_8     61878 non-null int64
feat_9     61878 non-null int64
feat_10    61878 non-null int64
feat_11    61878 non-null int64
feat_12    61878 non-null int64
feat_13    61878 non-null int64
feat_14    61878 non-null int64
feat_15    61878 non-null int64
feat_16    61878 non-null int64
feat_17    61878 non-null int64
feat_18    61878 non-null int64
feat_19    61878 non-null int64
feat_20    61878 non-null int64
feat_21    61878 non-null int64
feat_22    61878 non-null int64
feat_23    61878 non-null int64
feat_24    61878 non-null int64
feat_25    61878 non-null int64
feat_26    61878 non-null int64
feat_27    61878 non-null i

In [10]:
df.isnull()

id  feat_1  feat_2  feat_3  feat_4  feat_5  feat_6  feat_7  feat_8  \
0      False   False   False   False   False   False   False   False   False   
1      False   False   False   False   False   False   False   False   False   
2      False   False   False   False   False   False   False   False   False   
3      False   False   False   False   False   False   False   False   False   
4      False   False   False   False   False   False   False   False   False   
5      False   False   False   False   False   False   False   False   False   
6      False   False   False   False   False   False   False   False   False   
7      False   False   False   False   False   False   False   False   False   
8      False   False   False   False   False   False   False   False   False   
9      False   False   False   False   False   False   False   False   False   
10     False   False   False   False   False   False   False   False   False   
11     False   False   False   False   False   False   False   False   False   
12     False   False   False   False   False   False   False   False   False   
13     False   False   False   False   False   False   False   False   False   
14     False   False   False   False   False   False   False   False   False   
15     False   False   False   False   False   False   False   False   False   
16     False   False   False   False   False   False   False   False   False   
17     False   False   False   False   False   False   False   False   False   
18     False   False   False   False   False   False   False   False   False   
19     False   False   False   False   False   False   False   False   False   
20     False   False   False   False   False   False   False   False   False   
21     False   False   False   False   False   False   False   False   False   
22     False   False   False   False   False   False   False   False   False   
23     False   False   False   False   False   False   False   False   False   
24     False   False   False   False   False   False   False   False   False   
25     False   False   False   False   False   False   False   False   False   
26     False   False   False   False   False   False   False   False   False   
27     False   False   False   False   False   False   False   False   False   
28     False   False   False   False   False   False   False   False   False   
29     False   False   False   False   False   False   False   False   False   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
61848  False   False   False   False   False   False   False   False   False   
61849  False   False   False   False   False   False   False   False   False   
61850  False   False   False   False   False   False   False   False   False   
61851  False   False   False   False   False   False   False   False   False   
61852  False   False   False   False   False   False   False   False   False   
61853  False   False   False   False   False   False   False   False   False   
61854  False   False   False   False   False   False   False   False   False   
61855  False   False   False   False   False   False   False   False   False   
61856  False   False   False   False   False   False   False   False   False   
61857  False   False   False   False   False   False   False   False   False   
61858  False   False   False   False   False   False   False   False   False   
61859  False   False   False   False   False   False   False   False   False   
61860  False   False   False   False   False   False   False   False   False   
61861  False   False   False   False   False   False   False   False   False   
61862  False   False   False   False   False   False   False   False   False   
61863  False   False   False   False   False   False   False   False   False   
61864  False   False   False   False   False   False   False   False   False   
61865  False   False   False   False   False   False   False   False   False   
61866  Fal

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
from sklearn.cross_validation import train_test_split

In [14]:
X=df.drop('target',axis=1)

In [15]:
y=df['target']

In [17]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3,random_state=101)

In [18]:
rfc= RandomForestClassifier(n_estimators=200)

In [19]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [20]:
rfc_pred= rfc.predict(X_test)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix

In [22]:
print(classification_report(y_test,rfc_pred))

             precision    recall  f1-score   support

    Class_1       1.00      1.00      1.00       583
    Class_2       1.00      1.00      1.00      4836
    Class_3       1.00      1.00      1.00      2454
    Class_4       0.99      0.97      0.98       822
    Class_5       0.99      0.99      0.99       766
    Class_6       0.99      0.99      0.99      4194
    Class_7       0.96      0.98      0.97       839
    Class_8       1.00      1.00      1.00      2555
    Class_9       1.00      1.00      1.00      1515

avg / total       0.99      0.99      0.99     18564



In [23]:
print(confusion_matrix(y_test,rfc_pred))

[[ 582    1    0    0    0    0    0    0    0]
 [   0 4836    0    0    0    0    0    0    0]
 [   0    0 2454    0    0    0    0    0    0]
 [   0    0    2  794    5   20    1    0    0]
 [   0    0    1    2  762    1    0    0    0]
 [   0    0    0    4    1 4161   24    2    2]
 [   0    0    1    0    1   10  821    6    0]
 [   0    0    0    0    0    2    4 2548    1]
 [   0    0    0    0    1    0    1    4 1509]]
